### PR TITLE
Fix: copied sha needs to be trimed

### PR DESCRIPTION
**Pull request by randy3k**

### CODE REVIEW

**Comment by stoivo** [comment]
Looks good, but would like for someone to comment before we merge. I know it feels kind a stupid to do it for one line patches. Still I think we should make it as a practice and always follow it. 

Not tried to be harsh, just want to make an agreement.

**Comment by asfaltboy** [comment]
Also, a little background around this would help, e.g in the body of the commit or PR

**Comment by divmain** [comment]
Yep, let's wait for another reviewer to give their :+1:, except possibly in cases of emergency bug fixes.

**Comment by randy3k** [comment]
👌

**Comment by stoivo** [comment]
I concur

**Pull request merged**
