### PR TITLE
sanitize ansi sequences

### LINKED ISSUE #1020: Translate/strip color codes from push log
When pushing to a remote that responds with some build information (such as Heroku), color in the output is not displayed, but rather the raw color codes, e.g:
```
remote: <0x1b>[1;33m !! <0x1b>[0m
```
Only `!!` is the actual output here.

If you could either strip such data or use it to display actual colors, that would be great.

ST: 3176
Git: 2.19.0
OS: Arch, kernel 4.18.5

### PR DESCRIPTION
**Pull request by randy3k**
close #1020

as title, sanitize ansi sequences

### CODE REVIEW

**Comment by stoivo** [comment]
Do you think it make sense to do this for every command Gitsavvy called to git. I am thinking this may not be the bet this to do performance wise. I know is't a small thing but executed very frequent.

**Comment by randy3k** [comment]
This pr sanitizes ansi sequences for every command called by `self.git(...)`.

**Comment by stoivo** [comment]
Yes and it is wasiting resouces for 99.99% of all commands. Thinks works fine for you and me but we should't add uneccessary load.

**Comment by randy3k** [comment]
I believe that regular expression searches are quite efficient though.

**Comment by stoivo** [comment]
quite efficient but unneccearry, espcelly when we have a open issue about performance. https://github.com/divmain/GitSavvy/issues/653

**Comment by randy3k** [comment]
The slow performance is usually associated to slow disk access. I am not too worried about the performance hit here.

**Comment by stoivo** [comment]
It's probaly fine so we can merge it

**Pull request merged**
