### PR TITLE
Fix: Decode stdin to debug log

### PR DESCRIPTION
**Pull request by stoivo**
This bug was intoroduces in
  Other: refactor log_git and add log_ ...
  6fbefaf97720

### CODE REVIEW

**Comment by stoivo** [comment]
This should be pushed to packagecontroll.io since this will fix debug log for all users using inline diff

**Comment by stoivo** [comment]
Write a comment in #772 that this PR is merged.

**Comment by stoivo** [comment]
Since maintenerd in gone, make a release manually?

**Comment by stoivo** [comment]
We can add 
```
    "2.16.3": "messages/2.16.2.txt"
```
`2.16.3` to point to the same ad `2.16.4` if we think there are someone how was not updated yet. If we do that we will show `messages/2.16.2.txt` twice for those updating one by one.

**Comment by asfaltboy** [comment]
I believe we can skip updating messages all together. Just make a small hotfix branch off master, and cherry pick this PRs merge and done

**Comment by asfaltboy** [comment]
https://github.com/divmain/GitSavvy/releases/tag/2.16.3

All done, now package control should detect the tag and push the update.

**Pull request merged**
