### PR TITLE
Enhancement: offer push to remote rather than configuring remote

### LINKED ISSUE #738: Create pull request for unpushed branches should push them
Hey

Thanks for the excellent git integration, definitely the best I've seen for Sublime. As the co-author of a competitor, you've won me over and I've fully switched a while back. :)

At the moment if you try create a pull request for an unpushed local branch, it asks to set an upstream from existing remote branches. This means my workflow for upstreaming changes involves 4 steps: create local branch, make changes, push, create pull request.

I believe those last 2 steps can be streamlined by defaulting to the same as a push command when trying to create a pull request with an unpushed local branch. This would allow you to create a new remote branch (by default) matching your local branch name, and create a new pull request, all in 1 command.

### PR DESCRIPTION
**Pull request by randy3k**
Close #738 
when creating PR without tracking remote, prompt to push to remote instead of asking to configure remote tracking branch.

PS: this PR is created by this feature.

-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [x] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by stoivo** [comment]
What is the benefit of using WindowCommand instead of TextCommand, performance?

**Comment by randy3k** [comment]
We don't need any view to invoke these commands.

**Comment by randy3k** [comment]
Thanks @stoivo

**Comment by sheldon** [comment]
Thanks for the really quick implementation, this does exactly what I had in mind :)

**Pull request merged**
