### PR TITLE
Tag the line containing HEAD for styling purpopses

### PR DESCRIPTION
**Pull request by kaste**
I'm not super smart in this area. 

image

I just wanted to highlight the branch/tag thing in the graph view. After the fact, I thought maybe it's 'better' to mark the whole line. But I couldn't get that to work ~without spending too much time~ at all, I basically have no idea.

### CODE REVIEW

**Comment by kaste** [comment]
Would be nice to have it for the whole line, so I could mark the commit dot at the beginning of the line. 🤔

**Comment by randy3k** [comment]
Highlighting the whole line is possible, but it will be some work. The basic idea is to use `view.add_regions` to add a specific scope to the region (and erase it when the view is updated.)

**Comment by randy3k** [comment]
It would say it is good for this purpose now. Let's merge it.

**Comment by kaste** [comment]
Well, I thought I can just do a lookahead for '(HEAD ' and then mark that line using a meta-scope, and pop on '$'. Now, I already do such a look-ahead here but in the wrong place.

**Comment by kaste** [comment]
Sometimes you just have to write down the problem and then you get #1067

**Pull request merged**
