### PR TITLE
Convert directories with code to proper packages

### PR DESCRIPTION
**Pull request by asfaltboy**
Add `__init__` module to all directories with python modules.

This is mainly to make the relative imports make sense for my
anaconda/jedi when running goto/autocomplete commands.

I assume this would help us when we write unit tests as well

### CODE REVIEW

**Comment by randy3k** [comment]
Speaking of the tests, I will start working on a skeleton this weekend.

**Comment by stoivo** [comment]
Remove branch?

**Comment by asfaltboy** [comment]
@stoivo feel free to remove a merged branch, no commits will ever be lost.

**Comment by stoivo** [comment]
Next time I will do.

**Pull request merged**
