### PR TITLE
Next release

### PR DESCRIPTION
**Pull request by randy3k**
-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [ ] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [ ] All related documentation has been updated to reflect the changes made. _(required)_
- [ ] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [ ]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by randy3k** [comment]
@stoivo FYI, we don't need to review it until the next release, any new commits to `dev` will stale the approval.

**Comment by stoivo** [comment]
hehe, I did not see that this was the dev branch.

**Comment by randy3k** [comment]
The PR start date reminds me that it may be time to release a new release. Shall we freeze the dev channel for the next release?

**Comment by stoivo** [comment]
> Shall we freeze the dev channel for the next release?
Do you mean that we should not merge more PR into dev for the next week?

**Comment by randy3k** [comment]
We could checkout a new branch from dev for the next release.

**Comment by randy3k** [comment]
I am trying the use the git flow model: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by randy3k** [comment]
use #784 instead

**Pull request closed without merging**
