### PR TITLE
Fix: GsQuickCommitCommand is a WindowCommand

### LINKED ISSUE #996: quick commit not working?
- Sublime Text version number: 3.1.1
- Git version number: 2.17.1
- OS type and version: macOS high sierra, 10.13.6
- Console error output, 
```
Traceback (most recent call last):
   File "/Users/kcoelho/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/quick_commit.py", line 23, in <lambda>

   File "/Users/kcoelho/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/quick_commit.py", line 27, in on_done

   AttributeError: 'GsQuickCommitCommand' object has no attribute 'view'
```
- A description of the problem.

> Git quick commit does not work

- Steps to reproduce, if possible

> run the quick commit command.

- If the bug is caused by a failing command, [include a debug log](https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log). 

> I tried to follow the instructions but the log showed only `[]`.

### PR DESCRIPTION
**Pull request by randy3k**
@stoivo it is a bug introduced by the last release. Let's make a quick release for this one.

close #996

### CODE REVIEW

**Comment by stoivo** [comment]
@randy3k, you are a HERO!
I appriciate your hard work very much

**Comment by stoivo** [comment]
Should release a patch release with this hotfix without message?

**Comment by randy3k** [comment]
Good idea.

**Comment by randy3k** [comment]
Done: https://github.com/divmain/GitSavvy/releases/tag/v2.17.5

**Pull request merged**
