### PR TITLE
Fix: Pedantic commit checks allows comment on 2. line

### LINKED ISSUE #920: Commit syntax has weird highlighting
I see weird violet highlight of first comment line when committing. It shows up when there is something written on first (empty) line and there is no line break between it and the comment.

See the image:
git-commit-highlight

S3 b3161
git version 2.15.1 (Apple Git-101)
macOs 10.13

BTW. New S3 builds include syntax for commit messages and other git files. I wonder if it makes sense to use those instead.

### PR DESCRIPTION
**Pull request by stoivo**
fix #920

Should we patch this on master and release a patch release?

### CODE REVIEW

**Comment by randy3k** [comment]
If you want to release a patch release, we should merge it to master.

**Comment by stoivo** [comment]
Do we need to add a message? I dont think so

**Comment by randy3k** [comment]
Not necessary strictly speaking, but it is not hard to add one either.

**Comment by stoivo** [comment]
I will not add one since if someone dumps two versions it won't show up the first one.

**Pull request merged**
