### PR TITLE
feature: shorter path display

### PR DESCRIPTION
**Pull request by yyyc514**
- avoids really long absolutely paths in dashboards
- prefer to show ~ rather than the full path to a users home dir

### CODE REVIEW

**Comment by yyyc514** [comment]
```
BRANCH:  On branch `feature/shorter_root_path_display` tracking `origin/feature/shorter_root_path_display`.
  ROOT:    ~/Library/Application Support/Sublime Text 3/Packages/GitSavvy
  HEAD:    ee37d12 feature: shorter path display
```

**Comment by yyyc514** [comment]
I'm guessing either this magically works on windows or else it does no harm.

**Comment by yyyc514** [comment]
Unless it blows up with a key error?  This I might need to tweak this.

**Comment by yyyc514** [comment]
Rewritten to first check if the key exists.  The goal here (in case it's not clear) is a shorter/cleaner display of information.

**Comment by divmain** [comment]
This LGTM.  I'll pull down and merge manually, due to the conflict.

**Comment by yyyc514** [comment]
LGTM?

**Comment by divmain** [comment]
Sorry - "Looks Good To Me" :)

**Pull request merged**
