### PR TITLE
reuse existing views for interfaces

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
Attempt at #104.  Thoughts?

**Comment by yyyc514** [comment]
I'm thinking maybe every Interface takes a single named argument and that is `repository_path`?  We can't count on storing it in the view because an interface doesn't have a view until after we search for an existing view, and to do the search we need to know the repository_path (to build the view_path).

**Comment by yyyc514** [comment]
Rather than do a super complex comparison I just let ever interface set it's own view-path (should it be interface path?) then it loops over interfaces trying to match the path.

**Comment by yyyc514** [comment]
If you want to reuse the whole interface itself I'd have to go back and refactor this... right now a new Interface is created but it ties to find and use an existing view.

**Comment by divmain** [comment]
Closed in favor of ecabcad7b098097c6b626cc3d71d61423bec547e.

**Pull request closed without merging**
