### PR TITLE
Release/2.16.4

### PR DESCRIPTION
**Pull request by randy3k**
Let's use this PR for the next release.

-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [x] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by randy3k** [comment]
Shall I tag 2.17.0 instead?

**Comment by stoivo** [comment]
Cause it was new features 2.16.3 is ok since there are no super exciting features.

**Comment by randy3k** [comment]
I just imagine that there would be an urgent bug that we need to fix and that would be 2.16.3 instead. I've never used `git` flow` to manage a project, is it a more common practice to release a minor than a patch version?

**Comment by randy3k** [comment]
We need to also prepare a change log.

**Comment by randy3k** [comment]
Added a message file, please review again.

**Comment by randy3k** [comment]
it looks like maintainerd is not auto tagging the release.

**Comment by randy3k** [comment]
I pushed 2.16.4 manually https://github.com/divmain/GitSavvy/releases/tag/2.16.4

**Pull request merged**
