### PR TITLE
Internal: add syntax tests

### PR DESCRIPTION
**Pull request by randy3k**
-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [x] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by randy3k** [comment]
Appveyor is usually faster.
https://ci.appveyor.com/project/divmain/gitsavvy/build/1.0.805

**Comment by stoivo** [comment]
Cool, @randy3k can you explain how this works in https://github.com/randy3k/UnitTesting/blob/master/sbin/run_tests.py?
If this is the correct place to look?

**Comment by randy3k** [comment]
Um, that script triggers the [scheduler](https://github.com/randy3k/UnitTesting/blob/9d035b11f534f212d94c6a617a100eed841e3b63/unittesting/scheduler.py#L9-L9) then triggers this [command](https://github.com/randy3k/UnitTesting/blob/9d035b11f534f212d94c6a617a100eed841e3b63/unittesting/test_syntax.py#L12-L12).

**Comment by stoivo** [comment]
cool

**Pull request merged**
