### PR TITLE
Enhancement: update various docs

### PR DESCRIPTION
**Pull request by randy3k**
Please check for errors.

### CODE REVIEW

**Comment by stoivo** [comment]
Look fine to me, but english is't my first language so some else should check it.

**Comment by divmain** [comment]
This is awesome.  Thanks a ton!

**Comment by divmain** [comment]
Also @randy3k, feel free to create these feature branches in `divmain` rather than `randy3k`.  That way you don't have to update your remote's `master` branch whenever you're making changes.

**Comment by randy3k** [comment]
Got it, @divmain

I guess It's about time for the next release.

**Pull request merged**
