### PR TITLE
Internal: Refactor away show_commit_info from LogPanel

### PR DESCRIPTION
**Pull request by stoivo**
It is a lot more convenient to just set on_highlight.

When you need a different on_highligh you just overwrite the current one. Either
by a new call or as a kwargs to show_log_panel

For #956 to go easier

### CODE REVIEW

**Comment by stoivo** [comment]
@randy3k @asfaltboy

**Comment by randy3k** [comment]
In this way, we cannot disable `show_commit_info` by passing `on_highlight=None`.

**Comment by stoivo** [comment]
You would need to give it a callable like `on_highlight=lambda c: None`

**Comment by randy3k** [comment]
Maybe we could change line 426 to detect if kwargs https://github.com/divmain/GitSavvy/blob/c67bf8cc6ad981d5bd7e8f144f2dec4752f62177/core/ui_mixins/quick_panel.py#L360
has `on_highlight`

**Comment by randy3k** [comment]
Your are probably right, but a more straightforward solution is to check `kwargs`.
```
if "highlight" is not in kwargs:
    # default highlight
else:
    if kwargs["highlight"]:
        # use this
    else:
        # disable highlight
```

**Comment by stoivo** [comment]
What about 
```
def show_log_panel(entries, on_done, **kwargs):
    """
    Display log entries in quick panel with pagination, and execute on_done(commit)
    when item is selected. `entries` can be either a list or a generator of LogEnty.

    """
    _kwargs = {}
    for option in ['selected_index', 'limit']:
        if option in kwargs:
            _kwargs[option] = kwargs[option]

    for option in ['on_highlight']:
        if option in kwargs:
            _kwargs[option] = kwargs[option]
            if not callable(kwargs[option]):
                _kwargs[option] = lambda commit: None

    lp = LogPanel(entries, on_done, **_kwargs)
    lp.show()
    return lp

```

**Comment by randy3k** [comment]
it also works (but the second for loop has only one item so it is not necessary)

**Comment by stoivo** [comment]
I will commit is like 
```python
def show_log_panel(entries, on_done, **kwargs):
    """
    Display log entries in quick panel with pagination, and execute on_done(commit)
    when item is selected. `entries` can be either a list or a generator of LogEnty.

    """
    _kwargs = {}
    for option in ['selected_index', 'limit']:
        if option in kwargs:
            _kwargs[option] = kwargs[option]

    if not callable(kwargs['on_highlight']):
        _kwargs[option] = lambda commit: None

    lp = LogPanel(entries, on_done, **_kwargs)
    lp.show()
    return lp

```

**Pull request merged**
