### PR TITLE
dev_mode: Add debug trace facility controlled through "dev_trace" setting

### PR DESCRIPTION
**Pull request by abusalimov**
As a use case, add tracing to the `reload` module to get the output advertised in #408.

### CODE REVIEW

**Comment by divmain** [comment]
This is really interesting.  Thanks for your work on the debug mode stuff - it's not typically where we get contributions!

**Comment by stoivo** [comment]
You are so write. I started looking at this but I don't understand what is happening in 3bb59cb33da4f6e10fd4b0eb3df4c6361e936ff3. Can one of you explain it a bit and how to use it?

**Comment by divmain** [comment]
@stoivo, `trace` is essentially a wrapper around `print`, mostly adding formatted meta-data and consistent output.  In the context of this larger, it allows for pretty debug output when reloading like you see in https://github.com/divmain/GitSavvy/pull/408.

**Comment by stoivo** [comment]
How would you use it? 

When to use `dump_var` vs `trace`? That is the difference I don't see.

**Comment by abusalimov** [comment]
@divmain you're welcome! I was experimenting on inline diff view -> switched to refactoring `ui.py` -> encountered reloading issues -> switched to reload -> and here we are, debugging it :wink: 

@stoivo `trace` is essentially an ad-hoc replacement for the standard `logging`:
```py
log = trace.for_tag("reload")  # read as: logger = logging.getLogger(__name__)
```
And then scatter around `log()` calls. As like using the standard logging, one can filter the output using trace tags.

---

On the other hand, `dump` and `dump_var` are more like handy helpers during hacking, useful for printf-style debugging. Usage of these is not supposed to be checked into the repository.
```py
def some_nasty_stuff(foo):
    ... # the real logic

    # XXX remove!
    # and if something performs wrong:
    dump(foo)         # arg0 = ...
    dump(foo=foo)     # foo = ...

    # or, to show all arguments and local variables:
    dump(**locals())  # foo = ...
                      # bar = ...
```

`dump_var` is essentially an internal function outputting a single value, a call to `dump(foo=foo)` is then handled as `dump_var("foo", foo)`. The former is just a bit less to type. :)

**Comment by stoivo** [comment]
Thanks @abusalimov

**Pull request merged**
