### PR TITLE
Enable maintainerd

### PR DESCRIPTION
**Pull request by divmain**
Alright @stoivo @asfaltboy @randy3k, this thing is ready for a test run.  What this will do:

1. Auto-edit the description of new pull requests with the following checkboxes:
  a. I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
  b. All related documentation has been updated to reflect the changes made.
  c. My commit messages are cleaned up and ready to merge.
2. Require that all of these checkboxes are checked off before CI goes green.
3. Requires the submitter (or one of the maintainers) to select a semantic version that corresponds with the change represented by the pull request.
4. Enforce formatting guidelines for commit subjects:
  a. They must be between 8 and 72 characters long.
  b. They must start with one of `Fix`, `Enhancement`, `Feature`, `Internal`, or `Other`, followed by a colon.
5. Enforce formatting guidelines for commit messages:
  a. If multi-line, the second line must be empty.
  b. If multi-line all lines musts be between 0 and 72 characters long.
6. Auto-post a message asking the submitter for more information when the `not-enough-information` label is added to an issue.

Finally, it exposes as API to retrieve the selected semantic version for a given PR.  In CI, we can use this API to determine how to bump the version number, do that automatically, generate the release notes from the commit message, and push the new tag back to `origin`.  This will completely automate our release process, at the granularity of a PR.

Down the line, I'll be adding auto-closing of issues that have been labeled `not-enough-information` and which have received no reply after a specified period of time.

All of this came out of my need to streamline the maintenance process for my OSS projects: primarily [freactal](http://github.com/FormidableLabs/freactal), [Rapscallion](http://github.com/FormidableLabs/rapscallion), and GitSavvy.  I have a couple of other projects in the pipeline, and I wanted to get maintainerd more or less working before they are released.

Definitely interested in your feedback here.  Particular rules can be tweaked or removed.  And if you have ideas for other busywork that could be automated away, let me know and I'll include it.  maintainerd will see a public release after its been vetted on my own projects for a bit.

Thanks!

-----

Semver selection for auto-publish purposes:

- [x]  patch

### CODE REVIEW

**Comment by stoivo** [comment]
What is a .maintainerd file?

**Comment by divmain** [comment]
@stoivo, it is the config file to control the maintainerd bot. If you look at the config items, they correspond to the description in the PR.

**Comment by divmain** [comment]
Looks like I got the thumbs-up from @stoivo.  I'm going to merge and see how this goes.  Note that, unless I back this change back out:

- All pull requests will see `maintainerd` integration in the description.
- All merged pull requests will result in a semantic version bump (dependent on the PR's semvers selection) and a corresponding Git tag.

**Comment by asfaltboy** [comment]
@divmain I haven't gone over all the features yet, but it looks like a nice tool for maintainers.

One thing though, would we really want to tag a version for each merged PR ? Won't that result in an effective release to sublime users every time we merge?

**Comment by divmain** [comment]
@asfaltboy, yeah it'll only release when merging into `master`, as currently configured.  In the past (generally speaking), we've only queued up changes and waited to release because it takes time.  But, in most cases, if the PR is of high enough quality to be merged, it's high enough quality to be released.  And yeah, for larger changes that require iterative PRs, we can use development branches.  Does that seem reasonable?

**Comment by stoivo** [comment]
With all the things done on master now. Does this mean every time I merge a PR  we will make a new release? Is so, when do we write deploy messages?

**Comment by divmain** [comment]
We have three options:

1. Amend the deploy script so that it updates the `messages/*` files and `messages.json`.  This wouldn't be too hard, and it would automate another piece of GitSavvy maintenance.
2. We could manually update `messages/*` and `messages.json` periodically.  We would generate the changelogs in the same way as before, and features would be deployed before they were formally announced in the changelog.
3. Instead of auto-releasing into `GitSavvy`, we could create another packagecontrol.io package called `GitSavvy Edge`.  This package would remain up-to-date with `master`.  When desired, we could manually publish to the `GitSavvy` package.

I'm partial to the second and third options.  If you feel as though we'd be publishing a lot of new bugs, we should go with 3.  But hopefully our PR process is robust enough that most issues are caught before they're merged into `master` anyway, in which case 2 seems like a reasonable option.

**Comment by stoivo** [comment]
Yeah, i would like to avoid two packaces. I think se can autogenerate be release messages. Can we have a deploy checbox/flag on each PR? Or is this what documunataion only is for?

**Comment by asfaltboy** [comment]
I favor the second option, since auto-generated changelogs tend to be messy from my experience. However we would need to somehow remind ourselves to do it ever X releases or weeks, etc

**Pull request merged**
