### PR TITLE
Use Package Control dependencies manager instead of vendor

### PR DESCRIPTION
**Pull request by stoivo**
This can be run to update dependencies
subl --command 'satisfy_dependencies'

@randy3k, I am not sure how this will play in with test. Can you check?

### CODE REVIEW

**Comment by randy3k** [comment]
UnitTesting [supports installing][1] Package Control.

[1]: https://github.com/randy3k/UnitTesting-example/blob/59637cd21aa0fb20c62a25163f7b7492fcfccf95/.travis.yml#L37

**Comment by stoivo** [comment]
Merge?

**Comment by randy3k** [comment]
LGTM, but we have to also update the [README](https://github.com/divmain/GitSavvy#less-simple).

**Comment by stoivo** [comment]
Like this, or do you think we should write more.

**Comment by randy3k** [comment]
And Package Control needs to be installed first.

**Comment by asfaltboy** [comment]
It would be nice to have a separate testing section in README, perhaps outside the main README page.

**Comment by stoivo** [comment]
Should I add how to install Package Control
`import urllib.request,os,hashlib; h = 'df21e130d211cfc94d9b0905775a7c0f' + '1e3d39e33b79698005270310898eea76'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)`

@randy3k can you add write a section about testing.

**Comment by randy3k** [comment]
Let's merge it first. I will work on the testing section.

**Pull request merged**
