### PR TITLE
Release/2.17.0

### PR DESCRIPTION
**Pull request by randy3k**
Let's freeze the current `dev` branch and prepare a new release. We should aim to release this in a week to give it some final tests.

### CODE REVIEW

**Comment by stoivo** [comment]
I will start to use this branch.

**Comment by stoivo** [comment]
I merged https://github.com/divmain/GitSavvy/pull/894#pullrequestreview-104726062 into master since it is too good to leave it out for this release.

**Comment by randy3k** [comment]
@stoivo 
I just spotted another bug related to theme generator and pushed a fix 8f93f25
Please review again.

**Comment by stoivo** [comment]
ok, lets stale this branch now and test it and make a release.  

I will be away on the mountain in Jotunheimen, from Saturday until whole next week.

**Comment by randy3k** [comment]
I can't wait to release this. 🤓

**Comment by randy3k** [comment]
Let's 🚢 it

**Pull request merged**
