### PR TITLE
Feature: Compare commit against a different commit

### LINKED ISSUE #373: Git Diff against Specific Commit
Maybe I am just missing something obvious, but is there a way to view the differences against a specific commit, rather than just the most recent one?

### PR DESCRIPTION
**Pull request by randy3k**
This depends on #466 and #467. Close #373 

untitled
(the screen shot may be reflect the latest code)

### CODE REVIEW

**Comment by divmain** [comment]
Once #467 is merged, can you please rebase on top of master?  This will add a lot of noise to the history if merged as-is.

**Comment by randy3k** [comment]
Of course.

**Comment by divmain** [comment]
Alrighty, this needs to be rebased to strip out the duplicate commits.  But after that, I'll merge it in.  Thanks again!

**Comment by randy3k** [comment]
@divmain 
it is rebased.

**Comment by randy3k** [comment]
Looks like this can be consolidated with the Branch Commit Comparison view in https://github.com/divmain/GitSavvy/pull/392

**Comment by randy3k** [comment]
I have decided to rewrite this to combine with Branch Commit Comparison, will push a new PR instead.

**Comment by divmain** [comment]
:+1:

**Pull request closed without merging**
