### PR TITLE
Enhancement: do not update status bar for transient view

### LINKED ISSUE #726: Unable to determine Git repo path
I've been getting this error when I try to commit recently. 
I don't know how to reproduce, or what causes the error.
Tried to open/close sublime, with and without project. Nothing seems to help.

### PR DESCRIPTION
**Pull request by randy3k**
It should fix #726 finally.

To test its effect, open "Go to Anything" by <kbd>c-p</kbd> and hold the down arrow.

-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [x] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by asfaltboy** [comment]
Just checked out the PR (2405f81) and alas, the issue reproduces when scrolling fast through "Go to anything" panel. No errors or debug log entries are created, just a bottom panel with "Unable to determine Git repo path."

I've added a `print` call below the new if condition added, like so:

        window = self.view.window()
        if not window or \
            (self.view.file_name() and
                self.view == window.transient_view_in_group(window.active_group())):
            # it means it is an transient view of a regular file
            return

        print('Updating status bar (%s %s %s %s %s)' % (
            self.view, self.view.file_name(), window, window.active_group(),
            window.transient_view_in_group(window.active_group())
        ))

This prints out the following lines when I reproduce the issue (and sometimes without reproducing it):

<details>
<summary>Click to view print log...</summary>
<p>
```
Updating status bar (<sublime.View object at 0x10a1f06d0> /Users/pavel/dev/github/GitSavvy/git_savvy.py <sublime.Window object at 0x10a1ee2d0> 0 <sublime.View object at 0x10a1ee5d0>)
Updating status bar (<sublime.View object at 0x1090e6290> /Users/pavel/dev/github/GitSavvy/core/commands/inline_diff.py <sublime.Window object at 0x1078dd110> 0 <sublime.View object at 0x1078dd550>)
Updating status bar (<sublime.View object at 0x10a1e4050> /Users/pavel/dev/github/GitSavvy/core/interfaces/rebase.py <sublime.Window object at 0x10a1eab50> 0 <sublime.View object at 0x10a1eacd0>)
Updating status bar (<sublime.View object at 0x10799c950> /Users/pavel/dev/github/GitSavvy/docs/flow.md <sublime.Window object at 0x108817450> 0 <sublime.View object at 0x108817650>)
Updating status bar (<sublime.View object at 0x1090e6ad0> /Users/pavel/dev/github/GitSavvy/docs/misc.md <sublime.Window object at 0x1090a75d0> 0 <sublime.View object at 0x1090a7910>)
Updating status bar (<sublime.View object at 0x1090cab50> /Users/pavel/dev/github/GitSavvy/docs/status.md <sublime.Window object at 0x10a1f1690> 0 <sublime.View object at 0x10a1f1550>)
Updating status bar (<sublime.View object at 0x10a1f4cd0> /Users/pavel/dev/github/GitSavvy/messages/1.4.0.txt <sublime.Window object at 0x1090f8fd0> 0 <sublime.View object at 0x1090f89d0>)
Updating status bar (<sublime.View object at 0x1090dce90> /Users/pavel/dev/github/GitSavvy/popups/style.css <sublime.Window object at 0x1090d3090> 0 <sublime.View object at 0x1090d30d0>)
Updating status bar (<sublime.View object at 0x1090d8450> /Users/pavel/dev/github/GitSavvy/syntax/graph.sublime-syntax <sublime.Window object at 0x10a1f1990> 0 <sublime.View object at 0x10a1f1850>)
Updating status bar (<sublime.View object at 0x1088560d0> /Users/pavel/dev/github/GitSavvy/syntax/test/syntax_test_branch.txt <sublime.Window object at 0x1090c3e90> 0 <sublime.View object at 0x1090c3b50>)
Updating status bar (<sublime.View object at 0x10a1f1650> /Users/pavel/dev/github/GitSavvy/syntax/status.sublime-syntax <sublime.Window object at 0x1090a7250> 0 <sublime.View object at 0x1090a75d0>)
Updating status bar (<sublime.View object at 0x1078c9350> /Users/pavel/dev/github/GitSavvy/syntax/dashboard.sublime-syntax <sublime.Window object at 0x1090a0dd0> 0 <sublime.View object at 0x1090a0d90>)
Updating status bar (<sublime.View object at 0x1090e1790> /Users/pavel/dev/github/GitSavvy/popups/log_graph_view.html <sublime.Window object at 0x1090fb850> 0 <sublime.View object at 0x10a1e1990>)
Updating status bar (<sublime.View object at 0x10a1f1350> /Users/pavel/dev/github/GitSavvy/docs/flow.md <sublime.Window object at 0x10a229f90> 0 <sublime.View object at 0x10a229190>)
Updating status bar (<sublime.View object at 0x1090c4110> /Users/pavel/dev/github/GitSavvy/core/ui_mixins/__init__.py <sublime.Window object at 0x1090f5d10> 0 <sublime.View object at 0x1090f5290>)
Updating status bar (<sublime.View object at 0x10a22ce90> /Users/pavel/dev/github/GitSavvy/core/git_mixins/status.py <sublime.Window object at 0x10885bc10> 0 <sublime.View object at 0x10a1d7510>)
Updating status bar (<sublime.View object at 0x10a22f090> /Users/pavel/dev/github/GitSavvy/core/commands/show_file_at_commit.py <sublime.Window object at 0x1090f5990> 0 <sublime.View object at 0x1090c5b90>)
```
</p></details>

**Comment by asfaltboy** [comment]
I was thinking of another solution, since a view/window link can be broken at any time during an execution, perhaps we can use [some event hook/s][1] to catch that, set a view and wrap our commands in a "safe view" execution which would return (e.g raise an exception to be caught somewhere safe) if buffer is unusable.

[1]: http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener

**Comment by randy3k** [comment]
That's strange, my console does not print anything, did you reload the package?

**Comment by asfaltboy** [comment]
Yep, restarted GitSavvy..

**Comment by randy3k** [comment]
The only case that `Unable to determine Git repo` could show is `view.window()` has changed to a `None` value while in the middle of [`get_branch_status_short()`](https://github.com/randy3k/GitSavvy/blob/2405f81238417aa56cab6c400a2c8e14f84e9806/core/commands/status_bar.py#L71-L71). 

This PR should have stopped this transient view from triggering `gs_update_status_bar`. I guess it is because `GsStatusBarEventListener` now is running [asynchronously](https://github.com/randy3k/GitSavvy/blob/2405f81238417aa56cab6c400a2c8e14f84e9806/core/commands/status_bar.py#L11-L21) which was changed in ac217ee7e0ba. May be we should revert that.

**Comment by randy3k** [comment]
@asfaltboy, please try again with the reverted commit. Hope it works for you.

**Comment by randy3k** [comment]
Although it may not 100% fix the issue, it definitely helps. Perhaps we should merge this first and decide a better solution later?

**Comment by asfaltboy** [comment]
Yes, it helps with the "Go to anything" test, but it still happens when I simply click and close a preview file quickly. I don't have a principal issue with this PR, and I appreciate the work, but not sure if we should bother though, any change we introduce may break other use cases which we haven't tested...

**Comment by randy3k** [comment]
I will test this branch for a few more days before merging it. Thanks anyway.

**Pull request merged**
