### PR TITLE
Enhancement: Add setting to custom command to open in new buffer

### PR DESCRIPTION
**Pull request by stoivo**
Solves #610

### CODE REVIEW

**Comment by randy3k** [comment]
If the result of a git command is outputed to the buffer, I guess it would be helpful to have the option to set a specific syntax to the output. For example, it would be a `diff` or `show_commit` `sublime-syntax`.

**Comment by stoivo** [comment]
Yes, can the setting be the path to the sublime-syntax?

How would I write spec for this to coveralls test not to fail?

**Comment by divmain** [comment]
@stoivo don't worry about code coverage for now.  It's handy to see how a PR changes the metric, but until we invest serious time into test coverage, it should't be a blocker to merging.  Ping me on Gitter when this PR is ready, and I'll tweak the coveralls config to avoid this issue.

As to the merit of this PR, I'm on the fence.  Since folks are asking for it, I guess its okay.  But the problem may then become that people will expect full functionality that they'd have in a real GitSavvy diff view or commit view.  That would involve a much more significant effort.

_However,_ this is a small change to address a specific request, so its probably fine.

**Comment by asfaltboy** [comment]
@divmain I feel the same way! [Your recommendation][1] in #610 was spot on to provide the full functionality we have in the shot command, including diff syntax, etc.
I do however appreciate the work that went into this PR and feel we should enhance custom commands whenever they are inadequate, though we should probably also update documentation.

[1]: https://github.com/divmain/GitSavvy/issues/610#issuecomment-283261040

**Comment by stoivo** [comment]
I added syntax option. I think I would draw the line at interactive custom commands.

**Comment by stoivo** [comment]
Thanks, I saw that you merged master into this. I rebased on top of master and pushed again, to eliminate merge commits.

**Comment by asfaltboy** [comment]
Good catch! There should be a setting to make this button rebase instead of merge, i.e isaacs/github#88

**Pull request merged**
