### PR TITLE
Improve graph and blame syntaxes

### PR DESCRIPTION
**Pull request by gwenzek**
extension of #349

### CODE REVIEW

**Comment by stoivo** [comment]
This is good. We should also write some tests for our syntaxes.
There is a paragraph about it under Testing https://www.sublimetext.com/docs/3/syntax.html.

Links to some examples
https://github.com/sublimehq/Packages/blob/master/Python/syntax_test_python.py
https://github.com/sublimehq/Packages/blob/master/HTML/syntax_test_html.html
https://github.com/sublimehq/Packages/blob/master/JavaScript/syntax_test_js.js
https://github.com/sublimehq/Packages/blob/master/SQL/syntax_test_sql.sql
https://github.com/sublimehq/Packages/blob/master/Ruby/syntax_test_ruby.rb

**Comment by stoivo** [comment]
Grach looks good, but can you add a screenshot of who the syntax look?

**Comment by gwenzek** [comment]
Hi @stoivo, thanks for testing my changes.
I added a few tests in gwenzek/develop as you requested. I only did tests for graph/blame/branch for now. The others are coming soon.
Should I make another PR with the tests?  The simplest would be for you to checkout my repo on your computer for testing instead of creating PR each times.

**Comment by stoivo** [comment]
I merged your develop branch into sublime_syntax. You tests looks good.
Make a new PR for the other tests. 

We will probably make a new release with all this syntax fixes before we get to write tests for the other syntaxes.

**Pull request merged**
