### PR TITLE
Fix: added self.get_short_hash to honor core.abbrev settings

### LINKED ISSUE #641: Rebase: commit manipulation no longer works in certain situations
Recently the rebase view doesn't work on one of my repos any more. The error messages printed in the console:
> Traceback (most recent call last):
  File "core.interfaces.rebase in /Users/Allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 679, in run_async
  File "core.interfaces.rebase in /Users/Allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 504, in get_idx_entry_and_prev
UnboundLocalError: local variable 'selected_idx' referenced before assignment

The logs (with some information redacted):
```
[
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "  branch1\n  branch2\n  branch3\n  branch4\n* branch5\n  branch6\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "log", 
      "-6000", 
      null, 
      "--reverse", 
      "--format=%h%n%H%n%s%n%an%n%ae%n%at%x00%B%x00%x00%n", 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      "--no-merges", 
      null, 
      "--topo-order", 
      null, 
      "<Redacted SHA>..HEAD", 
      null, 
      null, 
      null
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n<Redacted SHA>\n<Redacted commit message>\nAllen Zeng\n<Redacted email>\n1493360704\u0000<Redacted commit message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted commit message>\nAllen Zeng\n<Redacted email>\n1493378358\u0000<Redacted message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted message>\nAllen Zeng\n<Redacted email>\n1493378381\u0000<Redacted message>\n\u0000\u0000\n\n<Redacted SHA>\n<Redacted SHA>\n<Redacted message>\nAllen Zeng\n<Redacted email>\n1493378394\u0000<Redacted message>\n\u0000\u0000\n\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "merge-base", 
      "<Redacted SHA>", 
      "HEAD"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "rev-parse", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "merge-base", 
      "HEAD", 
      "origin/branch2"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA>\n"
  }, 
  {
    "command": [
      "rev-list", 
      "--count", 
      "<Redacted SHA>..HEAD"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "4\n"
  }, 
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "  branch1\n  branch2\n  branch3\n  branch4\n* branch5\n  branch6\n"
  }, 
  {
    "command": [
      "show-ref", 
      "refs/heads/branch5"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted SHA> refs/heads/branch5\n"
  }, 
  {
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": ""
  }, 
  {
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "<Redacted path>\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }, 
  {
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": "", 
    "type": "git", 
    "stdin": null, 
    "stdout": "## branch5\n"
  }
]
```

Again, this doesn't happen in all repos.

Any help is appreciated!

### PR DESCRIPTION
**Pull request by randy3k**
A quick fix to #641, the function `get_short_hash` can be better written but it works for now.

close #641

### CODE REVIEW

**Comment by randy3k** [comment]
> I think we should always pass around the short version of a sha. Since we can always find the full one if we want to.

The same argument can be altered to 

```
I think we should always pass around the long version of a sha. Since we can always find the short one if we want to.
```

**Comment by stoivo** [comment]
Not exactly, the user usually wants to see the short one. And in those cases where we want to display the full one, we need to make a new call to git. If we had the long one we would need to call git for each sha. 

Since we can not convert a long sha to a short one in python. Mostly is is 7 and if the is a conflict is 8 and so on.

**Comment by stoivo** [comment]
Do you want to merge is?

**Comment by randy3k** [comment]
Sure.

**Pull request merged**
