### PR TITLE
Add the command `git: gui`.

### PR DESCRIPTION
**Pull request by zlsun**

### CODE REVIEW

**Comment by divmain** [comment]
Output on my machine:
```
> git gui
git: 'gui' is not a git command. See 'git --help'.

Did you mean one of these?
	pud
	pum
```

What version was the first to ship `git gui`?  Also, this seems to be a good use case for #83.  That's coming up soon in my queue - do you think that would suffice @zlsun?

**Comment by zlsun** [comment]
@divmain , sorry for my carelessness, Git Gui is a build-in tool on Windows but not Linux/OSX.
Custom commands looks like a good solution. I will wait for it.

**Comment by divmain** [comment]
No worries @zlsun!

**Comment by asfaltboy** [comment]
@zlsun  - Actually, [git-gui is based on Tcl/Tk](http://git-scm.com/docs/git-gui), and it is cross-platform-compatible; e.g.: it also work on my OSX and Fedora machines (as well as windows). 

@divmain - Can I ask which version of git you use? `git-gui` was in fact added since git 1.5 series. Since it's been at least 5 years now, I believe it's safe to assume most people will have it. Additionally, we can also test for existence of this tool (and others e.g `git flow`) before enabling command.

`git-gui` exposes 4 commands that wrap other git commands such as blame, diff, log, etc.
For example, I find `git gui` very useful in some specific cases such as blame "digging"; i.e.: it's trivial to perform "Blame parent commit" from within `git gui blame`.

**Comment by asfaltboy** [comment]
By the way, simply running `git gui` defaults to `git gui citool` which is for a single commit action, and is not that useful IMHO.

Perhaps we ought to add separate commands for `git gui blame`, `git gui browser` and `git gui citool` ?

**Comment by divmain** [comment]
This seems to be enough of an edge case that I'm inclined to consider this "complete" with the implementation of #83.

**Pull request closed without merging**
