### PR TITLE
Enhancement: refactor blame command

### PR DESCRIPTION
**Pull request by randy3k**
It replaces my earlier PR #717 by removing the syntax highlight code because of performance issue.

1. line forwarding (the cursor will follow via history instead of going to a random place)

2. use [f], [c] and [a] to switch between `detect within file`, `detect within commit` and `detect within all commits` instead of showing a panel to ask every time. The popup view is also modified to show less text.

3.  the options of the BlameActionCommand are renamed.

-----

The maintainers of this repo require that all pull request submitters agree and adhere to the following:

- [x] I have read and agree to the [contribution guidelines](https://github.com/divmain/GitSavvy/blob/master/CONTRIBUTING.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by stoivo** [comment]
I would very much like to go through it but I can't find the time now while I am traveling.

**Comment by randy3k** [comment]
No problem. Take your time

**Comment by stoivo** [comment]
I rebased to resolve merge conflicts and added a commit with some additions fix. My commit should be squashed into yours. Please pull it down and take the ownership if the commit again. I am not completely sure how I took the ownership but I think it was because I did `git commit` instead of `git rebase --contintue` while rebasing.

When I went through it now you did not really change that much, mostly for the better. It is good that we moved the selection of `detect_move_or_copy_within` into an after preference since mostly you would not change it. I do think it was better when you could see all the options and select one rather than tabbing through.

Is it possible for you to push a branch with these changes https://github.com/divmain/GitSavvy/pull/717/commits?

**Comment by randy3k** [comment]
Check again.

**Comment by randy3k** [comment]
the `--follow` option of the `git log` could be quite slow for a large project. Do we want to use the version without `--follow` as default and create a toggle/settings for following file name changes?

(cf, we also do not follow file name change in `git: log current file`)

**Comment by randy3k** [comment]
@stoivo what do you think about the --follow option?

**Comment by stoivo** [comment]
Maybe `--follow` is more dangerous than I thought first. I started out only working on GitSavvy which has less than 1,5 k commits. So turn it off by default seems alright.

I think most users would like to have --follow enabled so maybe have it on by default and option to turn it off?

**Comment by stoivo** [comment]
> Is it possible for you to push a branch with these changes  https://github.com/divmain/GitSavvy/pull/717/commits?

Possible?

**Comment by randy3k** [comment]
I don't understand. Why is it necessary?

**Comment by randy3k** [comment]
let's merge this first and discuss the --follow option later.

**Comment by randy3k** [comment]
let's merge this first and discuss the --follow option later.

**Comment by stoivo** [comment]
With `--follow` you have a better experience if the file name changes? maybe we can do --follow on a rescue.

**Pull request merged**
