### PR TITLE
Fix: use check-ref-format to check branch name validity

### PR DESCRIPTION
**Pull request by randy3k**
Instead of using a regular expression to validate branch name, use the git command `check-ref-format` to validate it. It should give a better result than using a regular expression.

### CODE REVIEW

**Comment by stoivo** [comment]
`check#-ref-fo#rma👍ta` is valid but doesn't work

**Comment by randy3k** [comment]
It works for me.
screen shot 2018-03-11 at 2 21 18 pm

**Comment by stoivo** [comment]
Good for you, I will check again soon.

**Comment by randy3k** [comment]
Thanks @stoivo

**Comment by stoivo** [comment]
On another bug
First, try to create a branch with name `hello one`. It fails then set it to `hello-one` and you get the exception in the console.
http://recordit.co/yhKxnUZaSL

**Comment by randy3k** [comment]
@stoivo 
I have refactored it and fixed some related bugs. Please check again.

**Pull request merged**
