### PR TITLE
First try to read with utf-8 then latin-1

### PR DESCRIPTION
**Pull request by stoivo**
Related to #594

### CODE REVIEW

**Comment by divmain** [comment]
This seems pretty reasonable.  Going to merge, and we can ask for feedback from those who reported the issue.

**Comment by bizoo** [comment]
Argh, why latin-1 ?
Please look at the last comment of #594, the encoding must be the current encoding of the view, not an arbitrary one.

**Comment by stoivo** [comment]
I would use the view encoding if it was an option, but in this case it is not a open file in a buffer. It is stdout from a command. I can't see how I can use this to find the encoding for the file. 
@bizoo, do you know how I can get it correct?

**Comment by stoivo** [comment]
@bizoo, https://github.com/divmain/GitSavvy/pull/603/files#diff-1d123c94cf2d78df2c8edace6fa6ee97R228 
Here I would open the file in a buffer, let sublime determine the encoding, then read the buffer and close it. I don't see what we are gaining on that. 

I want to say thanks you for commenting, @bizoo. I don't like working with encoding problems, so I am looking the the quickest solution. I very open for solution which make sure I never need to look back at this part of the code.

**Pull request merged**
