### PR TITLE
Release/2.18.0

### PR DESCRIPTION
**Pull request by randy3k**
Let's freeze the dev branch and tag a release. (I don't have time yet to improve the release message.)

A Christmas present to every GitSavvy users.

### CODE REVIEW

**Comment by kaste** [comment]
I'm objecting 'cleanup commit message' and 'check "nothing to commit"' as implemented. I know why they're there and roughly the use-case but they are poor/cheap implemented. 

'cleanup commit message' has the wrong default. It is destructive surprising for new users. T.i. a default setting can now lead to data loss for the end-user. It is a breaking change. It is costly because it adds a git call to every commit esp. as preparation before the commit view actually appears.

'check "nothing to commit"' is just cheap implemented. It is very costly in that it adds a (usually unnecessary) git call to the preparation phase before the commit view actually appears. I showed in #1060 that a '--dry-run' is always more expensive than just a 'diff'. Unfortunately, the 'dry-run' doesn't scale (at least on Windows). So the bigger the repo the slower the call (also in #1060). The 'dry-run' is not necessary if we do a 'diff' call anyway. And we do the 'diff' call by default. If the user doesn't want the diff call we can still do the 'diff' because it is at least faster than the 'dry-run'. Lastly, the UX here is bad. If you do now attempt a commit with "nothing to commit" it basically throws. T.i. it shows the typical error panel from a failing git command. At that point the user is not aware that she issued a commit run, or any other git command. Instead we should just open the usual commit view, and show "Nothing to commit" where we otherwise show the diff. The user then 'ctrl+w' to just close the view, or just stages something. Please note that such a mistake - t.i. attempting to commit when nothing is staged - is a daily routine for any user so we really shouldn't throw here. We need a frictionless experience.   Ideally we allow writing the commit message before any staging and update the diff below our comment as we stage/unstage hunks. (Please note at least, that I personally often write the long commit messages before staging anything. T.i. when writing the commit message takes half an hour itself, staging is not the main problem I'm facing.)

**Comment by randy3k** [comment]
Okay, perhaps we should revert the corresponding PRs and discuss them in the next release.

**Comment by stoivo** [comment]
I am experiencing double output in the live console
```
> /usr/local/bin/git push --set-upstream origin cash_register_ui:cash_register_ui
remote: 
remote: To create a merge request for cash_register_ui, visit:        
remote:   https://gitlab.xx.no/xx/xx/merge_requests/new?merge_request%5Bsource_branch%5D=cash_register_ui        
remote: 
To gitlab.xx.no:xx/xx.git
 * [new branch]          cash_register_ui -> cash_register_ui
Branch 'cash_register_ui' set up to track remote branch 'cash_register_ui' from 'origin'.
remote: 
remote: To create a merge request for cash_register_ui, visit:        
remote:   https://gitlab.xx.no/xx/xx/merge_requests/new?merge_request%5Bsource_branch%5D=cash_register_ui        
remote: 
To gitlab.xx.no:xx/xx.git
 * [new branch]          cash_register_ui -> cash_register_ui
Branch 'cash_register_ui' set up to track remote branch 'cash_register_ui' from 'origin'.

[Done in 2.39s]
```


These are my config
```
{
  "dev_mode": true,
	"vintageous_friendly": false,
	"git_graph_args":
	[
		"log",
		"--pretty=format:%h%d (%ar) by `%an` %s",
		"--graph",
    "--no-color"
	],
	"show_commit_diff": "full",
	"show_panel_for":
	[
		"_log",
		"commit",
		"apply",
		"pull",
		"push"
	],
	"live_panel_output": true,
	"tab_order":
	[
		"status",
		"branch",
		"graph",
		"rebase"
	],
	"show_stdin_in_output": true,
	"pedantic_commit": true,
  "show_full_commit_info": true,
}
```

**Comment by randy3k** [comment]
I also have the double output issue when `live_panel_output` is on.

**Comment by randy3k** [comment]
Are we ready to make a release?

**Comment by kaste** [comment]
Iirc the diffview has too many bugs in dev and is annoying to use. Especially cursor jumps after hunking.

I would recommend you take everything up to 49a82d51cc730a5737304128c584edfe6def8f06 from my PR. This should be uncontroversial bc it does not contain any bigger refactorings. It mostly fixes cursor jumping, adds undo.

**Comment by randy3k** [comment]
Perhaps, you should remove the commits after 49a82d5 from #1075 and prepare a separate PR for the rest. We could then review the trimmed PR and merge it into the release.

**Comment by kaste** [comment]
That's probably a good idea, @randy3k

**Comment by randy3k** [comment]
This release keeps rolling bigger because of the bugfixes @kaste pushes every day. 😄

**Comment by asfaltboy** [comment]
I would release it as is right now, to give the pending fixes to users and allow more wide-spread testing.

**Comment by randy3k** [comment]
@asfaltboy I will make a release once I get an approval

**Pull request merged**
