### PR TITLE
Fix: fix navigation offset and cursor location when view starts

### PR DESCRIPTION
**Pull request by randy3k**
Now, the cursor will be initialized correctly for all tabs.

### CODE REVIEW

**Comment by asfaltboy** [comment]
I literally just updated my `sublime-keymap` to missing j/k shortcuts and saw that you updated the PR, great work!

**Comment by randy3k** [comment]
Please test if the keys are working.  :)

**Comment by asfaltboy** [comment]
Of course, not only that, I merged in your last commit and bar a single swapped line it was identical to my own changes. BTW mark PR as [WIP] to avoid early merge.

**Comment by randy3k** [comment]
I didn't expect that someone will response that quick to my PR. I will do [WIP] next time. 😄

**Comment by asfaltboy** [comment]
Weekends are the busiest days of OSS!

Also, I'd like to add a `GsRebaseNavigateConflictsCommand` and make it seamlessly continue from navigate. I'll try to add that if you don't mind.

**Comment by randy3k** [comment]
Sure.

**Pull request merged**
