### PR TITLE
fix: reloading breaks interface refreshing

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by yyyc514** [comment]
Anything holding this up?

**Comment by yyyc514** [comment]
Order is going to matter more as the source grows, but this is a good start.  Another of my branches doesn't work without more explicit ordered because when you start to use the objects more freely you run into issues about the order in which the objects are imported into different files.

**Comment by divmain** [comment]
Lost track of this one.  Merging.

**Comment by yyyc514** [comment]
Thanks!

**Pull request merged**
