### PR TITLE
Feature: allow navigation through conflicting files in rebase view

### LINKED ISSUE #512: Feature: next/prev keyboard shortcuts should iterate over the conflict filenames
When a view shows conflicts in addition to commits (currently only in rebase), then I would love the next/prev <kbd>.</kbd>/<kbd>,</kbd> keys (or <kbd>j</kbd>/<kbd>k</kbd> when using vim friendly) to also iterate over these conflicting files instead of skipping them to next commit. Like this I can quickly get to a file that needs fixing without moving my fingers off the keys I'm on to press up/down.

### PR DESCRIPTION
**Pull request by asfaltboy**
fix #512

### CODE REVIEW

**Comment by randy3k** [comment]
It works. I guess it is also useful to navigate between conflicting blocks in a conflicting file when it is opened. Maybe a special keybind like <kbd>Super+Enter</kbd> to jump to the next conflicting block.

**Comment by asfaltboy** [comment]
Thanks for the review. I'm not aware of anyone opening a conflicting file and jumping between blocks, it's a bit arbitrary. I usually use my mergetool ([Sublimerge][1]) to start a 3-way diff and use their shortcuts to merge any conflicting blocks.

Also, I kind of dislike the complexity of the code, do you see any obvious way to simplify this?

[1]: http://www.sublimerge.com/

**Comment by stoivo** [comment]
I think we should leave the conflict resolving to a dedicated tool for that, like Sublmerge. I personally usually fix my conflict by change the conflicting files. Though i use  [Git Conflict Resolver](https://packagecontrol.io/packages/Git%20Conflict%20Resolver)  to find next and previous conflict.

**Comment by randy3k** [comment]
as we agree GitSavvy should not handle conflicts, this PR is merged and closed now.

**Comment by asfaltboy** [comment]
Not sure who's using that though. Myself, I configured SublimeMerge as my
mergetool so I just hit <kbd>M</kbd> to launch it and use their shortcuts
to navigate the 3 way diff.

**Pull request merged**
